// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-dash/FintechCmd.tsx": () => import("../components/mockups/admin-dash/FintechCmd.tsx"),
  "./components/mockups/admin-dash/OpsRoom.tsx": () => import("../components/mockups/admin-dash/OpsRoom.tsx")
};
